routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'home')->name('home');
Route::post('/', 'LoginController')->name('login');

Route::get('/sign/{family}', 'SignController@show')->name('sign.show');
Route::put('/sign/{family}', 'SignController@update')->name('sign.update');

Route::get('/contract', 'ContractController@create')->name('contract.create');
Route::post('/contract', 'ContractController@store')->name('contract.store');

Route::get('/summary', 'SummaryController@index')->name('summary.index');
Route::get('/summary/{family}', 'SummaryController@show')->name('summary.show');

// TODO: Fix le middleware
Route::middleware(['auth'])->group(function () {
});

app/Baby.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Baby extends Model
{
    protected $fillable = [
        'firstname',
        'birth_date',
        'expected_in',
        'expected_out'
    ];

    /**
     * Get the baby family
     */
    public function family()
    {
        return $this->belongsTo('App\Family');
    }

    /**
     * Get the signs of the baby
     */
    public function signs()
    {
        return $this->hasMany('App\Sign');
    }

    public function signsByMonth(Carbon $date)
    {
        $date = $date->copy();
        $date->tz('Europe/Paris');
        $year = $date->year;
        $month = $date->month;

        $stored_signs = $this->signs()->where('sign_date', 'like', "$year-%$month-%")->get()->sortByDesc('sign_date');
        $signs = [];
        $last = $date->copy()->lastOfMonth();

        for ($day = $date->firstOfMonth(); $day->lessThanOrEqualTo($last); $day->addDay()) {
            $sign = $stored_signs->firstWhere('sign_date', $day->format('Y-m-d'));

            $signs[] = ($sign) ?
                $sign :
                new Sign([
                    'sign_date' => $day->copy(),
                    'in' => 0,
                    'out' => 0
                ]);
        }

        return $signs;
    }

    /**
     * Get the today signs of the baby
     */
    public function todaySigns()
    {
        return $this->signs()->where('sign_date', date('Y-m-d'))->get()->first();
    }

    public function getFullNameAttribute()
    {
        return $this->family->lastname . ' ' . $this->firstname;
    }

    public function getAgeAttribute()
    {
        $now = new Carbon('now', 'Europe/Paris');
        $date = new Carbon($this->birth_date, 'Europe/Paris');

        $years = $now->diffInYears($date);
        $months = $now->diffInMonths($date->addYears($years));

        $fullAge = ($years > 0) ? $years . ' an' : '';
        $fullAge .= ($years > 1) ? 's' : '';
        $fullAge .= ($months > 0) ? ' ' . $months . ' mois' : '';

        return $fullAge;
    }

    public function getExpectedInFormatAttribute()
    {
        return (new Carbon($this->expected_in, 'Europe/Paris'))->format('H\hi');
    }

    public function getExpectedOutFormatAttribute()
    {
        return (new Carbon($this->expected_out, 'Europe/Paris'))->format('H\hi');
    }
}

app/Http/Controllers/SummaryController.php
<?php

namespace App\Http\Controllers;

use App\Family;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SummaryController extends Controller
{
    public function index()
    {
        return view('summary.index');
    }

    public function show(Request $request, Family $family)
    {
        $date = ($request->has('period')) ? Carbon::create($request->get('period')) : Carbon::now();
        $prev_period = $date->copy()->subMonthNoOverflow()->format('Y-m-d');
        $next_period = $date->copy()->addMonthNoOverflow()->format('Y-m-d');

        return view('summary.show', [
            'family' => $family,
            'period' => $date,
            'prev_period' => $prev_period,
            'next_period' => $next_period
        ]);
    }
}

resources/views/summary/index.blade.php
@extends('layouts.public')

@section('body')
    @include('views.login', [ 'route' => 'summary.show' ])
@endsection

resources/views/summary/show.blade.php
@extends('layouts.public')

@section('body')
    <main class="container">
        <h1>Récapitulatif</h1>
        <h2>Famille : {{ $family->lastname }}</h2>
        <h3>Période : {{ $period->startOfMonth()->format('d-m-Y') }} au {{ $period->endOfMonth()->format('d-m-Y') }}
        </h3>

        <a href="{{ route('summary.show', ['family' => $family->uuid, 'period' => $prev_period]) }}"
            class="btn btn-info m-3">Précédent</a>
        @if (is_null($next_period))
            <div class="btn btn-grey">Suivant</div>
        @else
            <a href="{{ route('summary.show', ['family' => $family->uuid, 'period' => $next_period]) }}"
                class="btn btn-info m-3">Suivant</a>
        @endif

        @foreach ($family->babies as $baby)
            <div class="card mb-2">
                <div class="card-body">
                    <div class="mb-2">
                        <span class="h4">{{ $baby->fullname }}</span>
                        <span class="h5 px-3">{{ $baby->age }}</span>
                        <span class="px-5">Heure d'arrivée estimée : {{ $baby->expected_in_format }}</span>
                        <span class="px-5">Heure de départ estimée : {{ $baby->expected_out_format }}</span>
                    </div>

                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Heure d'arrivée</th>
                                <th>Heure de départ</th>
                                <th>Temps suplémentaire</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($baby->signsByMonth($period) as $sign)
                                <tr>
                                    <td>{{ $sign->date }}</td>
                                    @if ($sign->timeIn == '00h00')
                                        <td colspan="2">Absent</td>
                                    @else
                                        <td>{{ $sign->timeIn }}</td>
                                        <td>{{ $sign->timeOut }}</td>
                                    @endif
                                    <td>{{ $sign->timeOver }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">Aucune donnée</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        @endforeach
    </main>
@endsection